// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID             uuid.UUID `json:"id"`
	SlotID         uuid.UUID `json:"slot_id"`
	UserID         uuid.UUID `json:"user_id"`
	Status         string    `json:"status"`
	ConferenceLink *string   `json:"conference_link"`
	CreatedAt      time.Time `json:"created_at"`
}

type Permission struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
}

type Role struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type RolePermission struct {
	RoleID       int16     `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type Room struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Capacity    *int      `json:"capacity"`
	CreatedAt   time.Time `json:"created_at"`
}

type Schedule struct {
	ID        uuid.UUID   `json:"id"`
	RoomID    uuid.UUID   `json:"room_id"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	CreatedAt time.Time   `json:"created_at"`
}

type ScheduleDay struct {
	ScheduleID uuid.UUID `json:"schedule_id"`
	DayOfWeek  int16     `json:"day_of_week"`
}

type Slot struct {
	ID        uuid.UUID `json:"id"`
	RoomID    uuid.UUID `json:"room_id"`
	StartTime time.Time `json:"start_time"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	RoleID       int16     `json:"role_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
