// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    name,
    description,
    capacity
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, description, capacity, created_at
`

type CreateRoomParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Capacity    *int    `json:"capacity"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.Description, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Capacity,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomList = `-- name: GetRoomList :many
SELECT 
    id,
    name,
    description,
    capacity,
    created_at
FROM rooms
ORDER BY name ASC
`

func (q *Queries) GetRoomList(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRoomList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Capacity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
