// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
WITH created_schedule AS (
    INSERT INTO schedules (
        room_id,
        start_time,
        end_time
    )
    VALUES (
        $1,
        $2,
        $3
    )
    RETURNING id, room_id, start_time, end_time, created_at
),
created_days AS (
    INSERT INTO schedule_days (
        schedule_id,
        day_of_week
    )
    SELECT
        created_schedule.id,
        unnest($4::smallint[])
    FROM created_schedule
    RETURNING day_of_week
)
SELECT
    created_schedule.id,
    created_schedule.room_id,
    created_schedule.start_time,
    created_schedule.end_time,
    created_schedule.created_at,
    array_agg(created_days.day_of_week ORDER BY created_days.day_of_week)::smallint[] AS days_of_week
FROM created_schedule
CROSS JOIN created_days
GROUP BY
    created_schedule.id,
    created_schedule.room_id,
    created_schedule.start_time,
    created_schedule.end_time,
    created_schedule.created_at
`

type CreateScheduleParams struct {
	RoomID     uuid.UUID   `json:"room_id"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
	DaysOfWeek []int16     `json:"days_of_week"`
}

type CreateScheduleRow struct {
	ID         uuid.UUID   `json:"id"`
	RoomID     uuid.UUID   `json:"room_id"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
	CreatedAt  time.Time   `json:"created_at"`
	DaysOfWeek []int16     `json:"days_of_week"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (CreateScheduleRow, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
		arg.DaysOfWeek,
	)
	var i CreateScheduleRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.DaysOfWeek,
	)
	return i, err
}
