// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSlots = `-- name: CreateSlots :exec
INSERT INTO slots (
    room_id,
    start_time
)
SELECT
    $1,
    unnest($2::timestamptz[])
ON CONFLICT (room_id, start_time) DO NOTHING
`

type CreateSlotsParams struct {
	RoomID     uuid.UUID   `json:"room_id"`
	StartTimes []time.Time `json:"start_times"`
}

func (q *Queries) CreateSlots(ctx context.Context, arg CreateSlotsParams) error {
	_, err := q.db.Exec(ctx, createSlots, arg.RoomID, arg.StartTimes)
	return err
}

const getUnbookedSlots = `-- name: GetUnbookedSlots :many
SELECT
    s.id,
    s.room_id,
    s.start_time,
    s.start_time + INTERVAL '30 minutes' AS end_time
FROM slots AS s
LEFT JOIN bookings AS b
    ON b.slot_id = s.id
    AND b.status = 'active'
WHERE b.id IS NULL
ORDER BY s.start_time
`

type GetUnbookedSlotsRow struct {
	ID        uuid.UUID `json:"id"`
	RoomID    uuid.UUID `json:"room_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   int32     `json:"end_time"`
}

func (q *Queries) GetUnbookedSlots(ctx context.Context) ([]GetUnbookedSlotsRow, error) {
	rows, err := q.db.Query(ctx, getUnbookedSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnbookedSlotsRow{}
	for rows.Next() {
		var i GetUnbookedSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
